export const QUERY_KEY = {
    USER: {
        GET_MY_INFO: "GET_MY_INFO",
        UPDATE_MY_INFO: "UPDATE_MY_INFO",
        CHANGE_PASSWORD: "CHANGE_PASSWORD"
    },
    AREA: {
        GET_AREAS: "GET_AREAS",
        GET_AREA: "GET_AREA",
        CREATE_AREA: "CREATE_AREA",
        UPDATE_AREA: "UPDATE_AREA",
        DELETE_AREA: "DELETE_AREA",
    },
    ROOM: {
        GET_ROOMS: "GET_ROOMS",
        GET_ROOM: "GET_ROOM",
        CREATE_ROOM: "CREATE_ROOM",
        UPDATE_ROOM: "UPDATE_ROOM",
        DELETE_ROOM: "DELETE_ROOM",
    },
    RENTEE: {
        GET_RENTEES: "GET_RENTEES",
        GET_RENTEE: "GET_RENTEE",
        CREATE_RENTEE: "CREATE_RENTEE",
        UPDATE_RENTEE: "UPDATE_RENTEE",
        DELETE_RENTEE: "DELETE_RENTEE",
    },
    COLLECTION: {
        GET_COLLECTIONS: "GET_COLLECTIONS",
        GET_COLLECTION: "GET_COLLECTION",
        GET_LATEST_COLLECTION: "GET_LATEST_COLLECTION",
        CREATE_COLLECTION: "CREATE_COLLECTION",
        UPDATE_COLLECTION: "UPDATE_COLLECTION",
        DELETE_COLLECTION: "DELETE_COLLECTION",
    },
}